import { SelectedResumeTemplateTypes } from "@/redux/types";
import ClassicHarmony from "@/templates/classic-harmony";
import CleanCanvas from "@/templates/clean-canvas";
import EssentialElegance from "@/templates/essential-elegance";
import NeatFusion from "@/templates/neat-fusion.template";
import SubtleSimplicity from "@/templates/subtle-simplicity.template";
import SimpleThirdTemplate from "@/templates/subtle-simplicity.template";
import TorontoTemplate from "@/templates/toronto.template";
import FuturaFlow from "@/templates/futura-flow";
import QuantumQuotient from "@/templates/quantum-quotient";
import FuturaFlow2 from "@/templates/futura-flow2";
import ChromaCraft from "@/templates/chromaCraft";
import MetroMatrix from "@/templates/metroMatrix";
import NoveHorizon from "@/templates/nova-horizon";

export const resumeTemplates: SelectedResumeTemplateTypes[] = [
  {
    templateImage: "/assets/images/templates/resumeTemplateFirst.webp",
    templateName: "Toronto",
    width: 333,
    height: 468,
    templateDetails:
      "The classic Harvard template, updated for the 21st century with a refined design that recruiters love and an optimized structure for improved ATS performance.",
    templateSections: {
      summary: true,
      experience: true,
      skills: true,
      education: true,
      interests: true,
      awards: true,
    },
    component: TorontoTemplate,
    templateColorsLength: 5,
    colors: {
      secondaryColor: "#FFFFFF",
      primaryColor: "#2871DE",
      templateFirstColor: "#FFFFFF",
      templateSecondColor: "#310CC3",
      templateThirdColor: "#31C30C",
      templateFourthColor: "#C3900C",
      templateFifthColor: "#C30C17",
      borderColor: "#1E62CB",
    },
    templateId: 213985,
    category: "simple",
  },
  {
    templateImage: "/assets/images/templates/resumeTemplateSecond.webp",
    templateName: "Neat Fusion",
    templateDetails:
      "If you want to highlight your extensive work history, this single-column resume template is an ideal choice.",
    width: 333,
    height: 468,
    templateSections: {
      summary: true,
      experience: true,
      education: true,
      languages: true,
      experties: true,
      references: true,
    },
    colors: {
      primaryColor: "#0e6cc2",
      templateFirstColor: "#FFFFFF",
      templateSecondColor: "#310CC3",
      templateThirdColor: "#31C30C",
      templateFourthColor: "#C3900C",
      templateFifthColor: "#C30C17",
      borderColor:'#F0CFC3'
    },
    templateColorsLength: 5,
    component: NeatFusion,
    templateId: 546218,
    category: "simple",
  },
  {
    templateImage: "/assets/images/templates/resumeTemplateThird.webp",
    width: 333,
    height: 468,
    templateName: "Subtle Simplicity",
    templateDetails:
      "The classic Harvard template, updated for the 21st century with a refined design that recruiters love and an optimized structure for improved ATS performance.",
    templateSections: {
      summary: true,
      experience: true,
      education: true,
      skills: true,
    },
    colors: {
      secondaryColor: "#F9F9F9",
      primaryColor: "#0E6CC2",
      templateFirstColor: "#FFFFFF",
      templateSecondColor: "#310CC3",
      templateThirdColor: "#31C30C",
      templateFourthColor: "#C3900C",
      templateFifthColor: "#C30C17",
      borderColor: "#3E0008",
    },
    component: SubtleSimplicity,
    templateColorsLength: 5,
    templateId: 968221,
    category: "simple",
  },
  {
    templateImage: "/assets/images/templates/ClassicHarmony.jpg",
    width: 333,
    height: 468,
    templateName: "Classic Harmony",
    templateDetails:
      "The classic Harvard template, updated for the 21st century with a refined design that recruiters love and an optimized structure for improved ATS performance.",
    templateSections: {
      summary: true,
      experience: true,
      education: true,
      skills: true,
    },
    colors: {
      secondaryColor: "#E4F6FB80",
      primaryColor: "#1C8EB5",
      templateFirstColor: "#FFFFFF",
      templateSecondColor: "#310CC3",
      templateThirdColor: "#31C30C",
      templateFourthColor: "#C3900C",
      templateFifthColor: "#C30C17",
      borderColor: "#1C8EB5",
    },
    component: ClassicHarmony,
    templateColorsLength: 5,
    templateId: 898373,
    category: "simple",
  },
  {
    templateImage: "/assets/images/templates/cleancanvas.webp",
    width: 333,
    height: 468,
    templateName: "Clean Canvas",
    templateDetails:
      "The classic Harvard template, updated for the 21st century with a refined design that recruiters love and an optimized structure for improved ATS performance.",
    templateSections: {
      summary: true,
      experience: true,
      education: true,
      skills: true,
    },
    colors: {
      secondaryColor: "#FFF2E480",
      primaryColor: "#CA6D18",
      templateFirstColor: "#FFFFFF",
      templateSecondColor: "#310CC3",
      templateThirdColor: "#31C30C",
      templateFourthColor: "#C3900C",
      templateFifthColor: "#C30C17",
      borderColor: "#CA6D18",
    },
    component: CleanCanvas,
    templateColorsLength: 5,
    templateId: 345347,
    category: "simple",
  },
  {
    templateImage: "/assets/images/templates/essentialresume.webp",
    width: 333,
    height: 468,
    templateName: "Essential Elegance",
    templateDetails:
      "The classic Harvard template, updated for the 21st century with a refined design that recruiters love and an optimized structure for improved ATS performance.",
    templateSections: {
      summary: true,
      experience: true,
      education: true,
      skills: true,
    },
    colors: {
      secondaryColor: "#7dc1ff",
      primaryColor: "#0E6CC2",
      templateFirstColor: "#FFFFFF",
      templateSecondColor: "#310CC3",
      templateThirdColor: "#31C30C",
      templateFourthColor: "#C3900C",
      templateFifthColor: "#C30C17",
      borderColor: "#3E0008",
    },
    component: EssentialElegance,
    templateColorsLength: 5,
    templateId: 4747649,
    category: "simple",
  },
  {
    templateImage: "/assets/images/templates/FuturaFlow.webp",
    width: 333,
    height: 468,
    templateName: "Futura Flow",
    templateDetails:
      "Progressive design for the forward-thinkers, blending innovation and style for a modern career narrative.",
    templateSections: {
      summary: true,
      experience: true,
      education: true,
      skills: true,
    },
    colors: {
      secondaryColor: "#E6E4E3",
      primaryColor: "#102D59",
      templateFirstColor: "#FFFFFF",
      templateSecondColor: "#310CC3",
      templateThirdColor: "#31C30C",
      templateFourthColor: "#C3900C",
      templateFifthColor: "#C30C17",
      borderColor: "#102D59",
    },
    component: FuturaFlow2,
    templateColorsLength: 5,
    templateId: 457484,
    category: "modern",
  },
  {
    templateImage: "/assets/images/templates/QuantumQuotient.webp",
    width: 333,
    height: 468,
    templateName: " Quantum Quotient",
    templateDetails:
      "Progressive design for the forward-thinkers, blending innovation and style for a modern career narrative.",
    templateSections: {
      summary: true,
      experience: true,
      education: true,
      skills: true,
    },
    colors: {
      secondaryColor: "#C6D9DF",
      primaryColor: "#003D74",
      templateFirstColor: "#FFFFFF",
      templateSecondColor: "#310CC3",
      templateThirdColor: "#31C30C",
      templateFourthColor: "#C3900C",
      templateFifthColor: "#C30C17",
      borderColor: "#C6D9DF",
    },
    component: QuantumQuotient,
    templateColorsLength: 5,
    templateId: 457481204,
    category: "modern",
  },
  {
    templateImage: "/assets/images/templates/chromaCraft.png",
    width: 333,
    height: 468,
    templateName: "Chroma Craft",
    templateDetails:
      "Progressive design for the forward-thinkers, blending innovation and style for a modern career narrative.",
    templateSections: {
      summary: true,
      experience: true,
      education: true,
      skills: true,
    },
    colors: {
      secondaryColor: "#F96B07",
      primaryColor: "#8A0202",
      templateFirstColor: "#FFFFFF",
      templateSecondColor: "#310CC3",
      templateThirdColor: "#31C30C",
      templateFourthColor: "#C3900C",
      templateFifthColor: "#C30C17",
      borderColor: "#F96B07",
    },
    component: ChromaCraft,
    templateColorsLength: 5,
    templateId: 457481209,
    category: "modern",
  },
  {
    templateImage: "/assets/images/templates/metroMatrix.png",
    width: 333,
    height: 468,
    templateName: "Metro Matrix",
    templateDetails:
      "Progressive design for the forward-thinkers, blending innovation and style for a modern career narrative.",
    templateSections: {
      summary: true,
      experience: true,
      education: true,
      skills: true,
    },
    colors: {
      secondaryColor: "#E16E68",
      primaryColor: "#E16E68",
      templateFirstColor: "#FFFFFF",
      templateSecondColor: "#310CC3",
      templateThirdColor: "#31C30C",
      templateFourthColor: "#C3900C",
      templateFifthColor: "#C30C17",
      borderColor: "#E16E68",
    },
    component: MetroMatrix,
    templateColorsLength: 5,
    templateId: 457481212,
    category: "modern",
  },
  // {
  //   templateImage: "/assets/images/templates/nove.webp",
  //   width: 333,
  //   height: 468,
  //   templateName: "Nova Horizon",
  //   templateDetails:
  //     " A cutting-edge template with dynamic sections, reflecting a modern approach to presenting skills and achievements.",
  //   templateSections: {
  //     summary: true,
  //     experience: true,
  //     education: true,
  //     skills: true,
  //   },
  //   colors: {
  //     secondaryColor: "#479099",
  //     primaryColor: "#000",
  //     templateFirstColor: "#FFFFFF",
  //     templateSecondColor: "#310CC3",
  //     templateThirdColor: "#31C30C",
  //     templateFourthColor: "#C3900C",
  //     templateFifthColor: "#C30C17",
  //     borderColor: "#479099",
  //   },
  //   component: NoveHorizon,
  //   templateColorsLength: 5,
  //   templateId: 457444581,
  //   category: "modern",
  // },
];

export default resumeTemplates;
